import type { Protocol } from "./types.js";

function hostnameFromBaseUrl(baseUrl: string): string {
  try {
    return new URL(baseUrl).hostname.toLowerCase();
  } catch {
    return "imported";
  }
}

/** Autogenerated IDs retain every hostname label and always identify the wire protocol. */
export function providerIdFromBaseUrl(baseUrl: string, protocol: Protocol): string {
  const slug = hostnameFromBaseUrl(baseUrl).replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return `${slug || "imported"}-${protocol}`;
}

export function providerNameFromBaseUrl(baseUrl: string, protocol: Protocol): string {
  return `${hostnameFromBaseUrl(baseUrl)} (${protocol})`;
}

/** Explicit IDs can update in place; automatically allocated IDs must never overwrite. */
export function availableProviderId(baseId: string, providers: Record<string, unknown>): string {
  let id = baseId;
  for (let n = 2; Object.hasOwn(providers, id); n++) id = `${baseId}-${n}`;
  return id;
}

/** True for bare UPPER_SNAKE names that apps may treat as env-var references (omp, prime). */
export function looksLikeEnvName(v: string): boolean {
  return /^[A-Z][A-Z0-9_]*$/.test(v);
}
